[package]

name = "dataflow-join"
version = "0.0.1"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies]
timely="0.7.0"
core_affinity = "0.5.9"
timely_sort="0.1.1"
time = "*"
rand = "0.5.5"
mmap="*"
